//filter
export const SELECT_FILTER_AREA = 'SELECT_FILTER_AREA';
export const SELECT_FILTER_SCHOOL = 'SELECT_FILTER_SCHOOL';
export const SELECT_FILTER_PROFESSION = 'SELECT_FILTER_PROFESSION';
export const SELECT_FILTER_YEAR = 'SELECT_FILTER_YEAR';
export const SELECT_FILTER_INTEREST = 'SELECT_FILTER_INTEREST';
export const SELECT_FILTER_SEX = 'SELECT_FILTER_SEX';
export const FILTER_STATUS = 'FILTER_STATUS';
//img
export const ALBUM_IMG_SRC = 'ALBUM_IMG_SRC';
//info
export const INFO_PERSONAL_INFO = 'INFO_PERSONAL_INFO';
