//filter
export const SELECT_FILTER_PROVINCE = 'SELECT_FILTER_PROVINCE';
export const SELECT_FILTER_CITY = 'SELECT_FILTER_CITY';
export const SELECT_FILTER_SCHOOL = 'SELECT_FILTER_SCHOOL';
export const SELECT_FILTER_PROFESSION = 'SELECT_FILTER_PROFESSION';
export const SELECT_FILTER_YEAR = 'SELECT_FILTER_YEAR';
export const SELECT_FILTER_INTEREST = 'SELECT_FILTER_INTEREST';
export const SELECT_FILTER_SEX = 'SELECT_FILTER_SEX';
export const FILTER_STATUS = 'FILTER_STATUS';
//img
export const ALBUM_IMG_SRC = 'ALBUM_IMG_SRC';
//info
export const INFO_PERSONAL_NAME = 'INFO_PERSONAL_NAME';
export const INFO_PERSONAL_AREA = 'INFO_PERSONAL_AREA';
export const INFO_PERSONAL_SCHOOL = 'INFO_PERSONAL_SCHOOL';
export const INFO_PERSONAL_PROFESSION = 'INFO_PERSONAL_PROFESSION';
export const INFO_PERSONAL_YEAR = 'INFO_PERSONAL_YEAR';
export const INFO_PERSONAL_INTEREST = 'INFO_PERSONAL_INTEREST';
export const INFO_PERSONAL_QRCODE = 'INFO_PERSONAL_QRCODE';
export const INFO_PERSONAL_STD_CARD = 'INFO_PERSONAL_STD_CARD';
export const INFO_PERSONAL_JOBS = 'INFO_PERSONAL_JOBS';
