//filter
export const SELECT_FILTER_PROVINCE = 'SELECT_FILTER_PROVINCE';
export const SELECT_FILTER_CITY = 'SELECT_FILTER_CITY';
export const SELECT_FILTER_SCHOOL = 'SELECT_FILTER_SCHOOL';
export const SELECT_FILTER_PROFESSION = 'SELECT_FILTER_PROFESSION';
export const SELECT_FILTER_YEAR = 'SELECT_FILTER_YEAR';
export const SELECT_FILTER_INTEREST = 'SELECT_FILTER_INTEREST';
export const SELECT_FILTER_SEX = 'SELECT_FILTER_SEX';
//img
export const ALBUM_IMG_SRC = 'ALBUM_IMG_SRC';
